//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogOfCards
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacients
    {
        public int Id { get; set; }
        public string NamePac { get; set; }
        public string SurnamePac { get; set; }
        public string DiagPac { get; set; }
    }
}
